name: Update gist with WakaTime stats

on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
  # Trigger the workflow on push events
  push:

jobs:
  update-gist:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 8322c0301f85a45e7acec045f6375b2f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
